site_name: RunUp
site_url: https://runup.readthedocs.io/

copyright: Copyright &copy; 2021 Kenny Lajara

edit_uri: ''

nav:
  - 'Home': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Setup': 'setup.md'
#  - 'Jobs': 'jobs.md'
  - 'Backup Creation': 'backup-creation.md'
  - 'Backup Restoration': 'backup-restoration.md'
  - 'License': 'license.md'

theme: readthedocs