# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload to PyPI

on:
  release:
    branches: [ main ]
    types: [published]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        sudo apt-get install -y patchelf
        python -m pip install --upgrade pip
        pip install cython
        pip install wheel
        pip install auditwheel
    - name: Build package
      run: |
        python3 setup.py sdist bdist_wheel
        auditwheel repair dist/RunUp-${{ github.event.release.tag_name }}-cp39-cp39-linux_x86_64.whl --plat manylinux2014_x86_64
        auditwheel repair dist/RunUp-${{ github.event.release.tag_name }}-cp39-cp39-linux_x86_64.whl --plat manylinux2014_i686
        auditwheel repair dist/RunUp-${{ github.event.release.tag_name }}-cp39-cp39-linux_x86_64.whl --plat manylinux2014_aarch64
        auditwheel repair dist/RunUp-${{ github.event.release.tag_name }}-cp39-cp39-linux_x86_64.whl --plat manylinux2014_ppc64le
        auditwheel repair dist/RunUp-${{ github.event.release.tag_name }}-cp39-cp39-linux_x86_64.whl --plat manylinux2014_s390x
        auditwheel repair dist/RunUp-${{ github.event.release.tag_name }}-cp39-cp39-linux_x86_64.whl --plat manylinux_2_24_x86_64
        auditwheel repair dist/RunUp-${{ github.event.release.tag_name }}-cp39-cp39-linux_x86_64.whl --plat manylinux_2_24_i686
        auditwheel repair dist/RunUp-${{ github.event.release.tag_name }}-cp39-cp39-linux_x86_64.whl --plat manylinux_2_24_aarch64
        auditwheel repair dist/RunUp-${{ github.event.release.tag_name }}-cp39-cp39-linux_x86_64.whl --plat manylinux_2_24_ppc64le
        auditwheel repair dist/RunUp-${{ github.event.release.tag_name }}-cp39-cp39-linux_x86_64.whl --plat manylinux_2_24_s390x
        rm dist/RunUp-${{ github.event.release.tag_name }}-cp39-cp39-linux_x86_64.whl
        rm dist/RunUp-${{ github.event.release.tag_name }}.tar.gz
        mv wheelhouse/* dist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN_RUNUP }} 
